# Generated by Django 5.2.1 on 2025-05-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('قيد التنفيذ', 'قيد التنفيذ'), ('مكتمل', 'مكتمل'), ('تحت الدراسة', 'تحت الدراسة')], default='قيد التنفيذ', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
